services:
  n8n-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-mcp-server
    environment:
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-60}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
    restart: unless-stopped