# Docker Stack deployment for production MCP Gateway integration
# Usage: docker stack deploy -c docker-stack.yml n8n-mcp

services:
  n8n-mcp-server:
    image: n8n-mcp-server:latest

    # Docker MCP Gateway mode configuration
    environment:
      - MCP_MODE=gateway
      - MCP_PORT=3000
      - DOCKER_SECRETS_PATH=/run/secrets
      - LOG_LEVEL=info
      - DEBUG=false
      - RATE_LIMIT_REQUESTS_PER_MINUTE=60
      - CACHE_TTL_SECONDS=300

    # Docker secrets (secure credential management)
    secrets:
      - source: n8n_api_key
        target: /run/secrets/n8n-api-key
        mode: 0400
      - source: n8n_base_url
        target: /run/secrets/n8n-base-url
        mode: 0400

    ports:
      - "3000:3000"

    # Docker MCP Gateway security requirements
    user: "1001:1001"
    read_only: false  # Required for temporary files

    # Resource constraints per Docker MCP specs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
          pids: 100
        reservations:
          cpus: '0.1'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 5s
        max_failure_ratio: 0.3

    # Health check for Docker Swarm
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service,version"

    # Placement constraints for production
    deploy:
      placement:
        constraints:
          - node.role == manager

# External secrets (created separately)
secrets:
  n8n_api_key:
    external: true
    name: n8n_api_key
  n8n_base_url:
    external: true
    name: n8n_base_url

# Network configuration
networks:
  default:
    name: mcp-gateway
    external: true
    driver: overlay
    attachable: true