version: '3.8'

services:
  # n8n MCP Server
  n8n-mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: n8n-mcp-server
    environment:
      - N8N_BASE_URL=${N8N_BASE_URL:-http://n8n:5678}
      - N8N_API_KEY=${N8N_API_KEY}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-n8n-mcp-server}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG=${DEBUG:-false}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-60}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
    depends_on:
      - n8n
    networks:
      - n8n-network
    restart: unless-stopped
    volumes:
      # Mount for stdio transport if needed
      - /dev/stdin:/dev/stdin
      - /dev/stdout:/dev/stdout
    
  # Example n8n instance (optional - you can use your existing n8n)
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-instance
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-password}
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    restart: unless-stopped

  # Optional: Gateway for multiple MCP servers
  mcp-gateway:
    image: nginx:alpine
    container_name: mcp-gateway
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n-mcp-server
    networks:
      - n8n-network
    restart: unless-stopped

volumes:
  n8n_data:

networks:
  n8n-network:
    driver: bridge