name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || echo "No linting configured"

      - name: Run type checking
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test || echo "No tests configured - TODO: Add tests"

      - name: Test Docker build
        run: |
          echo "Testing Docker build..."
          docker build --platform linux/amd64 -t test-build .
          echo "✅ Docker build successful"

      - name: Test Docker image startup
        run: |
          echo "Testing Docker image startup..."
          timeout 10s docker run --rm test-build || {
            if [ $? -eq 124 ]; then
              echo "✅ Image starts successfully (timeout expected for MCP server)"
            else
              echo "❌ Image failed to start"
              exit 1
            fi
          }

  validate-catalog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate catalog structure
        run: |
          echo "Validating catalog files..."

          # Check if catalog files exist
          if [ ! -f "catalog/n8n-server.yaml" ]; then
            echo "❌ catalog/n8n-server.yaml not found"
            exit 1
          fi

          if [ ! -f "catalog/server-definition.yaml" ]; then
            echo "❌ catalog/server-definition.yaml not found"
            exit 1
          fi

          # Install yq for YAML validation
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

          # Validate YAML syntax
          yq eval '.' catalog/n8n-server.yaml > /dev/null
          yq eval '.' catalog/server-definition.yaml > /dev/null

          # Check required fields in main catalog
          yq eval '.name' catalog/n8n-server.yaml | grep -q "n8n-mcp-catalog"
          yq eval '.displayName' catalog/n8n-server.yaml | grep -q "n8n MCP Server Catalog"
          yq eval '.registry."n8n-server".image' catalog/n8n-server.yaml | grep -q "eekfonky/n8n-mcp-server"

          # Check required fields in server definition
          yq eval '.image' catalog/server-definition.yaml | grep -q "eekfonky/n8n-mcp-server"
          yq eval '.tools | length' catalog/server-definition.yaml | grep -q "15"

          echo "✅ Catalog validation successful"